#spring:
#  data:
#    redis:
#      database: 0
#      host: 127.0.0.1
#      port: 6379

knife4j:
  enable: true
  setting:
    language: zh_cn

server:
  port: 9999

logging:
  level:
    com.nefu: debug
